### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by jairunet** [vlucaswang/pokemon_cafe#1]
Hello there @vlucaswang,

I just wanted to verify what I suppose to see when running the python program.  I appreciate if you could share where or how the notification will appear? in the terminal?

Having the notification does not mean I will be able to automate the booking process correct?

Thank you in advance,

**Comment by jairunet** [comment]
Oh and I just noticed the following error:
(pokemon_cafe-3.9.13) ➜  pokemon_cafe git:(main) python3 pokemon_cafe_check.py     


```
An error occurred: [Errno 8] Exec format error: './chromedriver'
Traceback (most recent call last):
  File "/home/user1/pokemon_cafe/pokemon_cafe_check.py", line 134, in <module>
    schedule.run_pending()
  File "/home/user1/.pyenv/versions/pokemon_cafe-3.9.13/lib/python3.9/site-packages/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/home/user1/.pyenv/versions/pokemon_cafe-3.9.13/lib/python3.9/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/user1/.pyenv/versions/pokemon_cafe-3.9.13/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/user1/.pyenv/versions/pokemon_cafe-3.9.13/lib/python3.9/site-packages/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "/home/user1/pokemon_cafe/pokemon_cafe_check.py", line 93, in check_availability
    driver.quit()  # Always quit the driver to close the browser
UnboundLocalError: local variable 'driver' referenced before assignment
```


I will try to debug it with ChatGPT and Gemini for now.

Thanks again for any suggestions,

**Comment by jairunet** [comment]
I am actually seeing this now:

```
(pokemon_cafe-3.9.13) ➜  pokemon_cafe git:(main) export MG_API_KEY=YOUR_MG_API_KEY                  
(pokemon_cafe-3.9.13) ➜  pokemon_cafe git:(main) python3 pokemon_cafe_check.py                      
No available slots found.
Finish Running
```
I am guessing the script will continue running until the next day at the 18:00 JST?

Thank you in advance,
